---
apiVersion: v1
kind: Secret
metadata:
  name: opaque-secret
type: Opaque
stringData:
  username: admin
  password: Pa55w0rd
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
type: kubernetes.io/basic-auth
stringData:
  username: superuser
  password: mybasicpass
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-secret
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN RSA PRIVATE KEY-----
    FAKE-KEY-FOR-DEMO
    -----END RSA PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    FAKE-CERT-FOR-DEMO
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    FAKE-KEY-FOR-DEMO
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-reg-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "myuser",
          "password": "mypassword",
          "email": "me@example.com",
          "auth": "bXl1c2VyOm15cGFzc3dvcmQ="
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: sa-token-secret
type: kubernetes.io/service-account-token
annotations:
  kubernetes.io/service-account.name: "my-service-account"
