apiVersion: v1
data:
  nginx.conf: |+
    # Minimal nginx.conf

    events {}

    http {
    server {
    listen 80;
    location / {
    return 200 'Hello from custom nginx.conf!\n';
    }
    }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
