apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: basic-auth
        secret:
          secretName: basic-auth
      containers:
      - name: nginx
        image: nginx:1.17.0
        volumeMounts:
        - name: basic-auth
          mountPath: /etc/secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "256m"
          limits:
            memory: "128Mi"
            cpu: "512m"
